### ISSUE TITLE
License and authorship information?

### ISSUE THREAD

**Issue by gonzalo-bulnes** [unman/shaker#24]
Hi @unman!

Thanks for sharing these states! I am keen on using some of them (starting by the `cacher` state) that I'd like to adapt to my own needs. I usually package my own states and make them public mostly for convenience ([example]), I'd be keen on doing the same with any work derived from yours.

I haven't found any copyright statement or license information in the repo, though:

- under which license(s) are you publishing this repository?
- what does the corresponding copyright statement look like?

If that helps, I'm happy to open a PR with that information if you tell me your preferences. 🙂

@tlaurion as the only other contributor listed, I assume you'd be fine with @unman's choice of license, but I'd ask you what's the copyright statement you prefer for your own contributions 🙂

  [example]: https://github.com/gonzalo-bulnes/qubes-mgmt-salt-user

**Comment by Asmith9555** [comment]
Looks like GPLv3 in most, if not all, of their spec files.

**Comment by gonzalo-bulnes** [comment]
You are right @Asmith9555, I overlooked the spec files! Remain to know which **copyright statements** to use to comply with the terms of the [GPL3-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html). 🙂
