### ISSUE TITLE
shaker, package manager and cacher not compatible with Q4.2

### ISSUE THREAD

**Issue by tlaurion** [unman/shaker#25]
Raw notes since I did a quick attempt overnight weeks ago.
- packages not avail for q4.2
- When installing 4.1 packages over q4.2, the installer is complaining about dependencies not being available
- Attempted to install cacher (life savor) but the policy file changed and q4.2 has a policy manager wchih parses the policies for update proxy and don't find it.

Basically q4.1 and q4.2 needs to be dealt separately.
I would also love if there was some guidance given so that qubes can have qubes-update-check+updates-proxy-setup enabled by default in services of newly created qubes, so that qubes can install applications from the cacher, to be reused in template if user decides he wants to install permanently, only downloading once and being reusable.

I understand that whonix won't use cacher. Not that of a problem.

Asking this now because wyng-qubes-util will support TLVM<->BRTFS restoration soon, and I would love to be able to test qubes install on BRTFS and have a basic setup working for me with my qubes and templates restored and just install new templates and replicate package installation on newly deployed templates. Since data is always a struggle, for me, cacher is a dependency.

BRTFS + bees holds some really valid promises, and is one of my priority to test.  I would love to prove a point that deduplication at pool level at restoration + BRTFS speed increase vs TLVM is a real thing, and that wyng-qubes-util is a lifesaver to backup, and restore on BRTFS when deduplication is in effect at pool level. Test would be pretty simple there. Backup everything and then restore on TLVM on another test laptop and compare consumed space.

All of this would be possible if cacher was there, available on Q4.2, which is progressing fast and seems to be becoming pretty stable!

**Comment by unman** [comment]
On Sat, Aug 05, 2023 at 08:24:14AM -0700, tlaurion wrote:
> Raw notes since I did a quick attempt overnight weeks ago.
> - packages not avail for q4.2
> - When installing 4.1 packages over q4.2, the installer is complaining about dependencies not being available
> - Attempted to install cacher (life savor) but the policy file changed and q4.2 has a policy manager wchih parses the policies for update proxy and don't find it.
> 
> Basically q4.1 and q4.2 needs to be dealt separately.
> I would also love if there was some guidance given so that qubes can have qubes-update-check+updates-proxy-setup enabled by default in services of newly created qubes, so that qubes can install applications from the cacher, to be reused in template if user decides he wants to install permanently, only downloading once and being reusable.
> 
> I understand that whonix won't use cacher. Not that of a problem.
> 
> Asking this now because wyng-qubes-util will support TLVM<->BRTFS restoration soon, and I would love to be able to test qubes install on BRTFS and have a basic setup working for me with my qubes and templates restored and just install new templates and replicate package installation on newly deployed templates. Since data is always a struggle, for me, cacher is a dependency.
> 
> BRTFS + bees holds some really valid promises, and is one of my priority to test.  I would love to prove a point that deduplication at pool level at restoration + BRTFS speed increase vs TLVM is a real thing, and that wyng-qubes-util is a lifesaver to backup, and restore on BRTFS when deduplication is in effect at pool level. Test would be pretty simple there. Backup everything and then restore on TLVM on another test laptop and compare consumed space.
> 
> All of this would be possible if cacher was there, available on Q4.2, which is progressing fast and seems to be becoming pretty stable!
> 

Thanks for this report.
I've not been able to do mmuch on 4.2 for reasons, but I will work on
this in the next few days, and let you know when it's there for
testing.
Thanks again

**Comment by tlaurion** [comment]
@unman any news?
