### ISSUE TITLE
Intended license for this project? 

### ISSUE THREAD

**Issue by tlaurion** [unman/shaker#26]
Shaker/tasks is being talked about on matrix for next QubesOS summit.

Questions that were asked are 
- intended license for shaker/tasks
- possible integration paths under QubesOS cummunity repo

That happened here and on https://matrix.to/#/!aYyyGgWwbaJfJexJtF:matrix.org/$rmhrXBRY0Sq5IAPCLX5pWkLDRa2ONu2OGbC0xdvh9iA?via=matrix.org&via=invisiblethingslab.com&via=envs.net

**Comment by tlaurion** [comment]
License are under spec files eg https://github.com/unman/shaker/blob/main/pihole.spec#L6

So GPLv3.
Could be more clearer by providing a license file

**Comment by ben-grande** [comment]
> So GPLv3.
> Could be more clearer by providing a license file

Although the spec says GPLv3+, everything is WTFPL v2 as per his profile license:

> All and any material in my Public repositories which are not forks is free.

- https://github.com/unman/shaker/issues/24#issuecomment-1600593746
- [unman/License](https://github.com/unman/unman/blob/master/License)
- [unman/COPYING](https://github.com/unman/unman/blob/master/COPYING)

Unman, can you please add the license and copying files to this repository and change the spec license?

I am making a project based on shaker and for now I am linking to  [unman/License](https://github.com/unman/unman/blob/master/License).

**Comment by unman** [comment]
Everything is WTFPL v2 
That does not preclude changing the license in the spec files.
