### ISSUE TITLE
Cacher update proxy throws error for some repos

### ISSUE THREAD

**Issue by unman** [unman/shaker#29]
With some repositories correctly configured to use cacher, updates fail.

The reported error is:
503 Server reports unexpected range [IP: 127.0.0.1:8082]

Updates fail for that repository because InRelease cannot be downloaded.
Other repositories update well.

Can be see with (e.g):
http://HTTPS///apt.syncthing.net

**Comment by ben-grande** [comment]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053833

Although Shaker is not cascading Acng, I think Syncthing repo does not set the HTTP header `If-Range` correctly.

Acng option `VfileUseRangeOps: 0` can be set to circumvent the Syncthing repository issue.

**Comment by unman** [comment]
Right

**Comment by ben-grande** [comment]
Fixed in 0a68a89df36cbee15e250475b4a760f4f4ec5ecd

**Comment by tlaurion** [comment]
@unman you can close
